version: '2'
services:
  web:
    build:
      context: .
    volumes:
        - ./:/var/app
        - bundle_cache:/usr/local/bundle
    ports:
        - '3000:3000'
    depends_on:
        - db
    environment:
      POSTGRES_URL: db
    tty: true
    stdin_open: true
  db:
    image: postgres:9.6.2-alpine
    ports:
        - '5432:5432'
    volumes:
        - postgres96:/var/lib/postgresql/data
volumes:
    postgres96:
    bundle_cache:
