version: '2'
services:
  web:
    build:
      context: .
    volumes:
        - ./:/var/app
        - bundle_cache:/usr/local/bundle
    ports:
        - '3000:3000'
    depends_on:
        - db
        - redis
    environment:
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: db
    tty: true
    stdin_open: true
  db:
    image: postgres:9.6.2-alpine
    ports:
        - '5432:5432'
    volumes:
        - postgres96:/var/lib/postgresql/data
  redis:
      image: redis
      ports:
          - '6379:6379'
      volumes:
          - redis:/data
volumes:
    postgres96:
    bundle_cache:
    redis:
